Was getting some stupid error from parallel in joblib because I stopped using fileprep in grid_coadd.py. Fixed.
AttributeError: 'numpy.ndarray' object has no attribute 'offset'
This was the error.